import React from 'react'

export default function Hatter() {
  return (
    <>
                <div
            aria-hidden="true"
            style={{
                position: 'absolute',
                left: '50%',
                top: '50%',
                width: '200vmax',        
                height: '30vmax',         
                transform: 'translate(-50%, -50%) rotate(135deg)',
                transformOrigin: 'center',
                background: 'linear-gradient(120deg, #0C2F29 0%, #00DF82 25%,#00FFCC 51%, #00DF82 75%, #0C2F29 100%)',
                zIndex: 0,
                pointerEvents: 'none',
            }}
                ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"5%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"10%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"15%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"20%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"24.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"29.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"34.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"39.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"44.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"49.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"54.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"59.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"64.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"69.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"74.9%"
        }}
        ></div>
         <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"79.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"84.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"89.9%"
        }}
        ></div>
        <div 
        style={{
            position:"absolute",
            height:"100%",
            width:`5%`,
            background:"rgba(10,36,36,0.2)",
            backdropFilter:"blur(40px)",
            WebkitBackdropFilter:"blur(40px)",
            left:"94.9%"
        }}
        ></div>
    </>
  )
}
